// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int64
	Name          pgtype.Text
	PhoneNumber   pgtype.Text
	Otp           pgtype.Text
	OtpExpiryTime pgtype.Timestamp
}
